import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import AppointmentActions from "./AppointmentActions";

export default async function BarberDashboardPage(){
 const session=await getSession();
 if(!session||(session.role!=="BARBER"&&session.role!=="ADMIN"))redirect("/login?next=/painel/barbeiro");
 const appointments=await prisma.$queryRaw<Array<{id:number;appointment_date:string;start_time:string;final_price:number;status:string;client_name:string|null;client_email:string|null;client_phone:string|null;favorite_cut:string|null;guest_name:string|null;guest_email:string|null;guest_phone:string|null;service_name:string}>>`
 SELECT a.id,DATE_FORMAT(a.appointment_date,'%Y-%m-%d') AS appointment_date,TIME_FORMAT(a.start_time,'%H:%i') AS start_time,a.final_price,a.status,u.name AS client_name,u.email AS client_email,u.phone AS client_phone,u.favorite_cut,a.guest_name,a.guest_email,a.guest_phone,s.name AS service_name
 FROM appointments a INNER JOIN services s ON s.id=a.service_id LEFT JOIN users u ON u.id=a.client_id
 WHERE a.appointment_date>=CURDATE() ORDER BY a.appointment_date ASC,a.start_time ASC LIMIT 30`;
 const today=new Date().toISOString().slice(0,10);const todayAppointments=appointments.filter(a=>a.appointment_date===today).length;
 return <main className="site-shell dashboard-shell"><section className="page dashboard"><div className="dashboard-head"><div><a className="back-link" href="/">← Início</a><span className="eyebrow">BARBER OF FRIENDS • ADMIN</span><h1 className="page-title">Olá, {session.name}.</h1><p className="page-subtitle">Central de controle da sua barbearia.</p></div><div className="actions"><a className="btn btn-primary" href="/agendar">Novo agendamento</a><form action="/api/auth/logout" method="post"><button className="btn btn-secondary">Sair</button></form></div></div><div className="stats-grid"><article className="stat glass"><span>Próximos</span><strong>{appointments.length}</strong><small>agendamentos</small></article><article className="stat glass"><span>Hoje</span><strong>{todayAppointments}</strong><small>atendimentos</small></article><article className="stat glass"><span>Operação</span><strong>Online</strong><small>painel protegido</small></article></div><section className="panel glass"><div className="panel-heading"><div><span className="eyebrow">AGENDA</span><h2>Próximos atendimentos</h2></div><a className="btn btn-primary" href="/agendar">Novo agendamento</a></div><div className="appointment-list">{appointments.length===0?<p className="page-subtitle">Nenhum agendamento futuro.</p>:appointments.map(a=>{const name=a.client_name||a.guest_name||"Cliente";const contact=a.client_phone||a.client_email||a.guest_phone||a.guest_email||"Contato não informado";return <div className="appointment" key={a.id}><div><strong>{name}</strong><span>{a.service_name} • {contact}</span>{a.favorite_cut&&<small>Favorito: <strong>{a.favorite_cut}</strong></small>}</div><time>{a.appointment_date.split("-").reverse().join("/")} às {a.start_time}</time><b className="appointment-price">R$ {Number(a.final_price).toFixed(2).replace(".",",")}</b><AppointmentActions id={a.id} status={a.status}/></div>})}</div></section></section></main>;
}
