"use client";

import { useEffect, useMemo, useState } from "react";

const key = (d: Date) => d.toISOString().slice(0, 10);
const label = (d: Date) => new Intl.DateTimeFormat("pt-BR", { weekday: "short", day: "2-digit", month: "short" }).format(d);
const slots = Array.from({ length: 24 }, (_, i) => { const m = 9 * 60 + i * 30; return `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`; });
const services = [{ name: "Corte normal", price: 45 }, { name: "Corte premium", price: 80 }];

export default function AgendarPage() {
  const [days, setDays] = useState<Date[]>([]); const [day, setDay] = useState(""); const [booked, setBooked] = useState<string[]>([]); const [time, setTime] = useState(""); const [service, setService] = useState("Corte normal"); const [guestName, setGuestName] = useState(""); const [guestPhone, setGuestPhone] = useState(""); const [guestEmail, setGuestEmail] = useState(""); const [logged, setLogged] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const now = new Date(); const list = Array.from({ length: 14 }, (_, i) => new Date(now.getFullYear(), now.getMonth(), now.getDate() + i)); setDays(list); setDay(key(list[0])); fetch("/api/appointments").then(r => r.json()).then(data => setBooked(data.map((a: { date: string }) => a.date))).catch(() => undefined); fetch("/api/auth/session").then(r => { setLogged(r.ok); }).catch(() => undefined); }, []);
  const unavailable = useMemo(() => booked.filter(v => v.startsWith(day)), [booked, day]);
  const isSunday = day ? new Date(`${day}T12:00:00`).getDay() === 0 : false;
  async function confirm() { if (!day || !time || isSunday) return; if (!logged && (!guestName.trim() || !guestPhone.trim())) { setMessage("Para agendar sem cadastro, informe nome e telefone."); return; } const date = new Date(`${day}T${time}:00`); const r = await fetch("/api/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date: date.toISOString(), service, guestName, guestPhone, guestEmail }) }); const data = await r.json(); if (!r.ok) { setMessage(data.error || "Não foi possível realizar o agendamento."); return; } setMessage(`Agendamento confirmado! ${data.discountPercent ? "Você recebeu 50% de desconto no corte premium. " : ""}Te esperamos na cadeira.`); setBooked(v => [...v, data.date]); setTime(""); }
  return <main className="site-shell"><section className="page booking-page"><a className="back-link" href="/">← Voltar</a><span className="eyebrow">BARBER OF FRIENDS • AGENDAMENTO</span><h1 className="page-title">Escolha seu horário.</h1><p className="page-subtitle">Atendimentos de 30 em 30 minutos, das 09:00 às 20:30. <strong>Domingo não possui agendamento.</strong></p><div className="calendar-row">{days.map(d => <button key={key(d)} disabled={d.getDay() === 0} className={`day-card ${day === key(d) ? "active" : ""}`} onClick={() => { setDay(key(d)); setTime(""); }}>{label(d)}{d.getDay() === 0 ? " • fechado" : ""}</button>)}</div><section className="booking-panel glass"><h2>Escolha o corte</h2><div className="service-grid">{services.map(item => <button key={item.name} className={`service-card ${service === item.name ? "selected" : ""}`} onClick={() => setService(item.name)}><strong>{item.name}</strong><span>R$ {item.price.toFixed(2).replace(".", ",")}</span></button>)}</div><p className="booking-hint">A cada 5 cortes concluídos com o barbeiro, o próximo corte premium recebe 50% de desconto.</p>{!logged && <div className="guest-fields"><h3>Se preferir, agende sem cadastro</h3><div className="form-grid"><input value={guestName} onChange={e => setGuestName(e.target.value)} placeholder="Seu nome" /><input value={guestPhone} onChange={e => setGuestPhone(e.target.value)} placeholder="Seu telefone" /><input value={guestEmail} onChange={e => setGuestEmail(e.target.value)} placeholder="Seu e-mail (opcional)" type="email" /></div><p>Já tem conta? <a href="/login">Entre para acessar seus agendamentos.</a></p></div>}<h2>Horários disponíveis</h2><div className="time-grid">{slots.map(t => { const occupied = unavailable.some(v => v.slice(0, 16).replace(" ", "T") === `${day}T${t}`); return <button key={t} disabled={occupied || isSunday} className={`time-slot ${time === t ? "selected" : ""}`} onClick={() => setTime(t)}>{t}{occupied ? " • ocupado" : ""}</button>; })}</div><div className="booking-footer"><span>{time ? `Selecionado: ${time}` : "Selecione um horário"}</span><button className="btn btn-primary" disabled={!time || isSunday} onClick={confirm}>Confirmar agendamento</button></div>{message && <p className="notice">{message}</p>}</section></section></main>;
}
